// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacebookAPI.Data;

#nullable disable

namespace SpacebookAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpacebookAPI.Model.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("viagem_destino");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("viagem_preco");

                    b.Property<string>("ViagemURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("viagem_url");

                    b.HasKey("Id");

                    b.ToTable("Viagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destino = "Lua",
                            Preco = 999.99m,
                            ViagemURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqyNKJF0L88y06-Tp-uVoTEx7jeN2FQc5Hfabmplt5kq1ypHbKKqvWUz6qH19fNrNy2g8&usqp=CAU"
                        },
                        new
                        {
                            Id = 2,
                            Destino = "Terra",
                            Preco = 999.99m,
                            ViagemURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHVfPD7xVOprUwv9cBB9Ub8R6DcQkTfj0RGNloEhvCJg&s"
                        },
                        new
                        {
                            Id = 3,
                            Destino = "Marte",
                            Preco = 999.99m,
                            ViagemURL = "https://media.istockphoto.com/id/1300652810/photo/mars-planet-3d-render-illustration-high-detailed-surface-features.jpg?s=612x612&w=0&k=20&c=V11fm3CB2JD1nmndQRTgBK-w4NOp72DXdxiOj2b9SHk="
                        },
                        new
                        {
                            Id = 4,
                            Destino = "Jupiter",
                            Preco = 999.99m,
                            ViagemURL = "https://t4.ftcdn.net/jpg/00/04/94/63/360_F_4946384_BOhNRo9oXd0KiN38sWXwIB72Rh8rzcv1.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
